# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-09 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0002_auto_20160609_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('obra_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('tipo_logradouro', models.CharField(choices=[('AVE', 'Avenida'), ('RUA', 'Rua'), ('PRA', 'Praça'), ('TRA', 'Travessa'), ('ROD', 'Rodovia'), ('VIL', 'Vila')], max_length=3)),
                ('nome_logradouro', models.CharField(max_length=30)),
                ('complemento', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=8)),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('progresso', models.TextField()),
                ('condicoes', models.TextField()),
                ('acidentes', models.TextField()),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.Cidade')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.Equipamento')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.Fornecedor')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.Funcionario')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.Material')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.Pagamento')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.Setor')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.Tarefa')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.Uf')),
            ],
        ),
    ]
